defaults:
  - _self_
  - callbacks: defaults
  - data: defaults
  - hydra: defaults
  - logger: defaults
  - loss: defaults
  - metrics: defaults
  - model: bert
  - module: defaults
  - optimizer: defaults
  - trainer: defaults

task_name: "train"